In [38]:
import numpy as np
from matplotlib import pyplot as plt

In [24]:
#Create a array in np
a=np.array([1,2,3,4,5])

In [3]:
a

array([1, 2, 3, 4, 5])

In [4]:
print(type(a))

<class 'numpy.ndarray'>


In [7]:
print(a.dtype)
print(a.shape)

int64
(5,)


In [15]:
a=np.array([[1,2],[3,4],[5,6]],dtype=np.uint8)

In [20]:
print(a.shape)
print(a)

(3, 2)
[[1 2]
 [3 4]
 [5 6]]


In [18]:
b=np.array([[1],[2],[3],[4],[5]])

In [19]:
print(b)
print(b.shape)

[[1]
 [2]
 [3]
 [4]
 [5]]
(5, 1)


In [22]:
b[2][0]

3

In [25]:
a[0]

1

In [27]:
c=np.array([[1,2,3],[4,5,6]])
print(c)
print(c.shape)
print(c[1][1])

[[1 2 3]
 [4 5 6]]
(2, 3)
5


In [35]:
#Create Zeroes, ones, custom array
a=np.zeros((3,3))
print(a)
b=np.ones((2,3))
print(b)

#Array of some constants
c=np.full((3,2),5)
print(c)

#Identity matrix
d=np.eye(4)
print(d)

#Random Matrix
randomMatrix=np.random.random((2,3))
print(randomMatrix)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[5 5]
 [5 5]
 [5 5]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[0.81625528 0.41530661 0.48842788]
 [0.06760374 0.90692113 0.12068491]]


In [55]:
# to perform slicing on rowwise and columnwise
print(randomMatrix[:,2])

[0.48842788 0.12068491]


In [57]:
#for updating particular elements
randomMatrix[1,1:]=1

In [58]:
print(randomMatrix)

[[0.81625528 0.41530661 0.48842788]
 [0.06760374 1.         1.        ]]


In [62]:
##Set some rows and columns with any values
z=np.zeros((3,3),np.int64)
print(z)
z[1,:]=3
z[:,2]=7
print(z)

[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[0 0 7]
 [3 3 7]
 [0 0 7]]


In [63]:
# Datatypes
print(z.dtype)

int64


In [66]:
# Mathematical operations
x=np.array([[1,2],[3,4]])
y=np.array([[5,6],[7,8]])
print(x+y)
print(np.add(x,y))
print(x-y)
print(np.subtract(x,y))

[[ 6  8]
 [10 12]]
[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[-4 -4]
 [-4 -4]]


In [70]:
print(x*y)
print(np.multiply(x,y))#element-wise multiplication
print(x/y)
print(np.divide(x,y))
print(np.sqrt(x))

[[ 5 12]
 [21 32]]
[[ 5 12]
 [21 32]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[1.         1.41421356]
 [1.73205081 2.        ]]


# Matrix Multiplication/ Dot product

In [73]:
print(x,y,sep='\n')

print(x.dot(y))
print(np.dot(x,y))

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [99]:
#Multiplication of vectors gives a scalar value
a=np.array([1,2,3,4])
b=np.array([1,2,3,4])
print(np.dot(a,b))

30


In [76]:
print(a)

[1 2 3 4]


In [77]:
print(sum(a))

10


In [84]:
print(x)
print(np.sum(x))
print(np.sum(x,axis=0))
print(np.sum(x,axis=1))

[[1 2]
 [3 4]]
10
[4 6]
[3 7]


In [100]:
#Stacking of arrays
print(a)
b=np.array([2,4,6,8])
b=b**2
print(b)

[1 2 3 4]
[ 4 16 36 64]


In [101]:
print(np.stack((a,b),axis=1))
print(np.stack((a,b),axis=0))
#when axis =0 row wise stacking else column wise stacking

[[ 1  4]
 [ 2 16]
 [ 3 36]
 [ 4 64]]
[[ 1  2  3  4]
 [ 4 16 36 64]]


In [102]:
# Reshape a numpy array
a=np.stack((a,b),axis=0)
print(a)

[[ 1  2  3  4]
 [ 4 16 36 64]]


In [106]:
a=a.reshape((4,2))
print(a)

[[ 1  2]
 [ 3  4]
 [ 4 16]
 [36 64]]


In [104]:
a=a.reshape((8,1))
print(a)

[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 4]
 [16]
 [36]
 [64]]


In [107]:
a=a.reshape((8,))
print(a)

[ 1  2  3  4  4 16 36 64]


In [108]:
a=a.reshape((4,-1))
print(a)

[[ 1  2]
 [ 3  4]
 [ 4 16]
 [36 64]]


In [109]:
a=a.reshape((-1,4))
print(a)

[[ 1  2  3  4]
 [ 4 16 36 64]]
