# Some more numpy functions
- min,max
- mean
- median
- average
- variance
- standard deviation

In [1]:
import numpy as np

In [8]:
a=np.array([[1,2,3,4],[7,6,2,0]])
print(a)
print(np.min(a))
#specify axis for the direction
print(np.min(a,axis=0))
print(np.min(a,axis=1))

[[1 2 3 4]
 [7 6 2 0]]
0
[1 2 2 0]
[1 0]


In [17]:
# mean
b=np.array([1,2,3,4,5])
n=sum(b)/len(b)

In [24]:
print(np.mean(a,axis=0))
print(np.mean(a,axis=1))
print(sum(a)/len(a))

[4.  4.  2.5 2. ]
[2.5  3.75]
[4.  4.  2.5 2. ]


In [25]:
c=np.array([1,2,4,5,0])
print(np.median(c))

2.0


In [31]:
# mean vs average which is weighted
print(np.mean(c))
w=[10,20,30,40,50]
print(np.average(c,weights=w))

2.4
2.466666666666667


In [36]:
#standard deviation
u=np.mean(c)
myStd=np.sqrt(np.mean(abs(c-u)**2))
print(myStd)

#Inbuilt Function for standard deviation
dev=np.std(c)
print(dev)

#variance
v=myStd**2
print(v)
print(np.var(c))

1.854723699099141
1.854723699099141
3.440000000000001
3.4400000000000004
